version: "3"
services:
  db:
    image: postgres:16
    container_name: db
    restart: always
#    volumes:
#      - "postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: exchange_rates_api
    command: ["/exchange_rates_api/docker/app.sh"]
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "nc", "-z", "db", "5432"]
      interval: 10s
      timeout: 5s
      retries: 30

#volumes:
#  postrges:
