version: "3"
services:
  db:
    image: postgres:16
    container_name: db
    command: -p 3131
    restart: always
#    volumes:
#      - "postgres:/var/lib/postgresql/data"
    expose:
      - 3131
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: exchange_rates_api
    command: ["/exchange_rates_api/docker/app.sh"]
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - db

#volumes:
#  postrges:
