version: "3"
services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    command: -p 3131
#    volumes:
#      - "postgres:/var/lib/postgresql/data"
    ports:
      - 3131:5432
    expose:
      - 3131
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "3131", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5 

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: exchange_rates_api
    restart: always
    ports:
      - 8001:8000
    depends_on:
      db:
        condition: service_healthy
    command: ["/exchange_rates_api/docker/app.sh"] 
    healthcheck:
      test: ["CMD", "nc", "-z", "db", "3131"]
      interval: 10s
      timeout: 5s
      retries: 30

#volumes:
#  postrges:
